apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}"
subjects:
- kind: ServiceAccount
  name: "{{ .Release.Name }}"
  namespace: test
roleRef:
  kind: ClusterRole
  name: "{{ .Release.Name }}"
  apiGroup: rbac.authorization.k8s.io
